# Narration v4 — about the work, not the working (2026-09-26):
#   no series callbacks, commits, test counts, logs or roadmap talk.
# Based on v3 — plain, flowing prose (human direction, 2026-09-26):
# "use longer sentences, stop writing everything using hooks".
#
# What changed from v2 (narration_v2.py, kept for the record):
#   - full sentences that connect their ideas (because / which / so / while / although)
#     instead of strings of short fragments
#   - no hooks: no one-word or fragment sentences, no dramatic "..." holds, no "So..." or
#     "Well..." openers, no set-up questions answered in the next line
#   - facts identical to v2 and to SOURCES.md; the required intro line (CLAUDE.md §8) kept verbatim
#
# Kokoro note (CLAUDE.md §4): commas buy only a short pause, so long sentences are held together
# by their grammar, not by punctuation. Listen to every beat; if one runs together, split that
# sentence at its connective, or try --speed 0.92-0.95 on that beat alone (hints below).

NARR_M8 = {
    "B00": "Hi, I am Divij Pawar, and this video is about a stricter way of comparing two AI agents and the test that it failed. The narration you're hearing is AI generated, but the work it describes is mine. The comparator I had built earlier removed fifteen of sixteen false alarms on a set of labelled runs, so I replayed those same sixteen runs through a stricter comparator, which raised six alarms instead of one and so failed the bar I had set for it, although along the way it found two real errors that the older rule had been hiding.",
    "B01": "The system runs two AI agents on the same company and compares the numbers they report, and until now most of the alarms it raised were false. This work makes that comparison rigorous, and all of it comes down to one test, which is that two figures can only be compared when they agree on what they measure, which period they cover, what unit they're in, and where they came from.",
    "B02": "I started with the period, by checking what the SEC data layer had actually been handing to the agents, and found that it asked for the latest value of each figure and got back a bare number with no period or unit attached. For Apple, the revenue it passed along was from fiscal twenty eighteen, under a label Apple stopped using years ago, and the earnings per share of six eighty-eight was really nine months added together, when the quarter itself was two oh two. Net income was year to date as well, and since nothing told the agents any of this, every Apple comparison the system had run until now was built on these figures.",
    "B03": "Now every figure carries its period, its unit, the filing it came from, and that filing's accession number, quarters are chosen by how many days they actually span, and when a company restates a number, the restated value wins. I wrote the failing test first, against a real Apple payload, so that it pins down both of the wrong choices the old rule was making.",
    "B04": "The fourth part of the test is the source, and here the problem was that the web search tool reports some failures by returning an error message rather than raising an error. Because the code only watched for raised errors, a failed search was recorded as a success and the error text was handed to the model as though it were a search result. Now a failed search gets one retry using only the query, and that retry brings back real results.",
    "B05": "The two agents also used to run one after the other, and now they run at the same time. On a live Apple run they started one millisecond apart and worked side by side for thirty-nine seconds, which shows that they really do overlap, although it doesn't show that a run finishes any faster.",
    "B06": "The metric and the unit come next, and the new comparator reads each number the way an analyst would, by working out what it's a figure of, which period it covers, and how close two values need to be before they count as the same. Earnings per share has to match to the cent, larger figures get half a percent of room for rounding, and two agents quoting different quarters are shown as different periods rather than flagged as a conflict. In a test built from Microsoft's filing, eighty-two point nine billion and eighty-two billion, eight hundred eighty-six million now count as the same figure, and on a stored Nvidia run, a model's rating of its own confidence at ninety percent no longer counts as a financial figure at all.",
    "B07": "One open problem was that a real ratio and a made-up one looked exactly the same to the system, so now, when only one agent states a ratio, the system recomputes it from that agent's own figures. Two Apple runs claimed an asset turnover of zero point one three and zero point one two, but the revenue and assets they reported in the same paragraph work out to zero point six nine, which is more than five times higher. Two Google runs stated a return on assets of eighteen point eight five, which recomputes to eighteen point nine six and is close enough to be cleared.",
    "B08": "That brings me to the correction. The old tagger saw the word assets inside the phrase return on assets and filed those ratios under assets, and then it skipped them, because assets was a figure that only one agent had been given. That's how two wrong ratios passed as clean, which means the earlier result of fifteen out of sixteen still stands, but part of it was produced by that mistake.",
    "B09": "The bar for the new rule was that it had to do no worse than the old one on the sixteen labelled runs, and it did worse, raising six alarms where the old rule raised one. One of those six is a genuinely fabricated debt-to-equity ratio of zero point three four, which both rules catch, but the other five are ratios stated without the figures behind them, and there's no way to say who was right, because those runs never recorded what each agent had been given.",
    "B10": "Because of that result, the new comparison is computed and shown on every company record, while the recorded verdict still comes from the old rule, and the screen always says which rule decided. Every run now also stores what each agent was given, which is exactly the information needed to settle cases like those five on future runs.",
    "B11": "The live runs also turned up three problems with the format of the answers. Agents were copying the prompt's own instructions into their answers, which seventeen of a hundred thirty-five stored conclusions had done, so the prompt now leaves the answer tags empty and a check rejects copied text. One version of the prompt also led the model to close its answer with square brackets in three of twenty-two first attempts, and when the model began its reasoning in the same turn as a web search, that opening was being dropped, so the parser now reads the earlier turns too, and the final batch finished with no first-attempt failures across eight agents.",
    "B12": "The comparison now appears as a table, where each figure gets its own row, with agent A in blue, agent B in orange, and the difference in the column between them. Figures that only one agent was given are folded away so they're never mistaken for a disagreement, and the headline at the top is counted from those rows rather than written by a model.",
    "B13": "Most of the earlier false alarms came from the two agents never being handed the same figure, so now both of them are given net income and diluted earnings per share. On Apple, for the first time in company mode, both agents cited the same figure from the same filing and agreed with each other and with the filing, although on Nvidia and Google one agent said that figure was missing, even though it was on the last line of its input.",
    "B14": "Several things work now that didn't before. Every figure carries its period, its unit, and its filing, failed searches are recorded as failures, the two agents run at the same time, and ratios are recomputed, which surfaced two real errors that had been hidden.",
    "B15": "Some things still don't work. The stricter comparator is still opt-in for company runs, tagging still depends on wording, the ratio check doesn't yet account for annual versus quarterly figures, and agents still skip figures they were given, even when those figures are right there in their input.",
    "B16": "The smallest true claim I can make is that the comparator became stricter and lost its own test, while also catching two errors that the easier rule had been hiding. Before trusting a match between two numbers, it's worth checking what each one measures, which period it covers, what unit it's in, and where it came from, and the decision about which rule counts here still belongs to a person.",
    "B17": "The rule that lost, written down, versioned, and executable. Signing off, Divij Pawar.",
}

NARR_M9 = {
    "B00": "Hi, I am Divij Pawar, and this video is about what happens when two AI agents disagree and a person has to decide between them. The narration you're hearing is AI generated, but the work it describes is mine. This run asked two agents when the first Pokémon game reached North America, and one of them said nineteen ninety-eight while the other said nineteen ninety-six. The system flagged the disagreement and then stopped, and it has been waiting for a person to decide ever since.",
    "B01": "Part one made the comparison between the two agents stricter, so that figures are now compared by metric, period, unit, and source. This part is about what happens when that comparison finds a real disagreement, because flagging a contradiction is only useful if something actually happens next. A gate like this needs a trigger you can test, a stop that actually holds, a named person who gives a written reason, and a record nobody can edit, and without all four it's really just a warning.",
    "B02": "The trigger is deliberately narrow, so a run only waits when two agents cite different values for the same figure and the same period, while a figure that only one agent mentions is shown for review without stopping anything, because there's nothing to decide between. Runs stored before the gate existed are never gated after the fact, since changing the rules on old records is how audit trails get rewritten, and in practice most runs never reach the gate at all.",
    "B03": "The decision form opens in the same place you're already reading, so it never covers the evidence. The reviewer picks one of five outcomes, which are that agent A is right, that agent B is right, that both are wrong, that there's no real conflict, or that the correct value is something they enter themselves, and then they have to give their reasoning in at least twenty characters, which is deliberately too long for something like looks good, before typing their name.",
    "B04": "The small print under the name field says that it's recorded as entered and not verified, because the login only carries a permission level and not an actual person, and the screen says that every time. If a decision breaks one of the rules, it's refused and the reason is explained in words, so a decision about a figure that nobody disputed is turned away rather than quietly fixed.",
    "B05": "A later decision can supersede an earlier one, but both stay on the record, because the database itself blocks edits and deletions.",
    "B06": "While a run is waiting, an investor sees the figures the agents agreed on along with a notice, and the server withholds the disputed values and both agents' answers. When I searched the investor's view of this run, nineteen ninety-six never appeared, but nineteen ninety-eight appeared once, inside a search result shown in the run's trace, so the trace now withholds what each search returned while the gate is open, and after that fix the same search finds neither year. The withholding still depends on read access, because a request without a token is served at the level the run was stored with.",
    "B07": "Nobody has recorded a decision on that run yet, so it is still open, which is exactly how the gate is meant to behave until a person looks at it.",
    "B08": "Two agents can agree with each other and still both be wrong, so each agent's figures are also checked against accounting identities, such as basic earnings per share never being lower than diluted, free cash flow equalling operating cash flow minus capital spending, and assets equalling liabilities plus equity. When an agent's figures break one of those, the run waits for a person just as it does for a mismatch, and the reviewer can confirm the error instead of picking an agent.",
    "B09": "Every figure an agent cites is also checked against the filing it was given, and rounding to the number of digits the agent wrote is allowed. In one Microsoft run, an agent was given revenue of eighty-two point nine billion and wrote eight hundred twenty-eight point nine billion. That attempt failed its format check first, so this check never actually ran on it, but it would have caught the mistake if it had.",
    "B10": "Other rules only describe what is usually true. On one Google run, net income came out at nearly three times operating income, and the filing showed the same thing, because it reflected a real one-off gain. That's why rules like this never stop a run and only mark the result as unusual and worth a look. The same finding also explained two figures that part one had left unrecognised, which turned out to be Google's filed earnings per share.",
    "B11": "The filing itself goes through the same checks, using the single fetch that has already been made, and Apple's balance sheet adds up. In the middle of this testing, though, the local model stopped responding, to the point where a five-token test request got no reply within sixty seconds, and because model calls have no timeout, a stuck model can hold up a comparison indefinitely.",
    "B12": "Every figure the agents were given can now be found in the original filing, because the system opens the actual SEC document, finds the exact tagged value, and returns the row, the column, and the number as it was filed. In the last batch it found all twenty-four figures and every filed value matched, and in the review each figure now has a source button that opens that excerpt in place, while web figures show the snippet the agent actually read.",
    "B13": "You can also watch a comparison as it happens. Each agent has its own lane showing what it's doing at that moment, and the single shared SEC fetch is drawn only once, because it only happened once. Every indicator on that screen comes from a real server event.",
    "B14": "Analysts don't stop at the figures, because they also make a call, so after each answer passes its checks, a second call to the same model reads that answer and extracts a grade, a direction, the stated assumptions, and up to three key points, all labelled as model judgment. Anything it quotes that isn't in the agent's own answer or inputs is dropped, and when the extraction fails, the run carries on and says so.",
    "B15": "When two grades differ, the system works out whether the agents used different figures or periods, used the same figures with different assumptions, or differed on neither, in which case it comes down to how they weighed the same evidence. A consensus is only recorded when both the grade and the direction agree and no hard rule has failed, and anything else goes to the gate, where the reviewer can accept one agent's grade or set the grade themselves, while investors see no grade until a person has recorded one.",
    "B16": "The review now reads in the order a person needs it, starting with the answer and whether anything failed a check, followed by the decision, then the evidence figure by figure, then the agents, and finally the underlying machinery, which is folded away. Every review can also be exported as a plain document.",
    "B17": "Several things work now that didn't before. A mismatch, a failed hard check, or a grade disagreement stops the run until a person decides, decisions need a reason and can't be edited, and investors don't receive the disputed values, either agent's answer, or anything the searches returned. Accounting rules check each agent and the filing, and every review can be exported as a plain document.",
    "B18": "Some things still don't work. The decider's name is typed in and never verified, and anyone can create a reviewer token, which is a known security gap. The storage still holds everything and the withholding only happens when the data is read, the grade extraction is the same model judging its own answer, and model calls still have no timeout.",
    "B19": "The judgment stays with a person, and this is the first time the system can't move forward without one. The smallest true claim I can make is that the machine fetches, reads, compares, checks and grades, and then it stops and waits. If you run agents yourself, take one warning your system raises, give it a trigger, a stop, a person, and a record, and then check that it can't clear itself. For now, this one run is still open.",
    "B20": "One run, still open, written down, versioned, and executable. Signing off, Divij Pawar.",
}

# Long sentences raise the slur risk, so the hint now covers the densest beats in both reels.
SPEED_IF_SLURRED_M8 = {b: 0.94 for b in ("B01", "B02", "B04", "B06", "B07", "B11")}
SPEED_IF_SLURRED_M9 = {b: 0.94 for b in ("B01", "B03", "B06", "B08", "B15")}
