# Narration v2 — rewritten for a natural spoken read on Kokoro (am_onyx).
#
# Rules applied (fellows/divij-pawar/CLAUDE.md §4):
#   - one independent clause per sentence, ended with a real period (the only mark Kokoro
#     reliably pauses on); subordinate clauses and short phrases are fine inside a sentence
#   - "..." only for a genuinely held beat (a reveal, a turn); never an em dash (it becomes ", ")
#   - contractions, sentence-initial connectors (So / And / But / Now), rhetorical questions and
#     varied sentence length, so it reads like a person talking instead of a list
#   - no "it's not X, it's Y"; facts identical to v1 (see SOURCES.md)
#
# SPEED_IF_SLURRED: per CLAUDE.md, --speed 0.92-0.95 is the fix for a beat that still slurs
# after the text is right, applied to that beat only (never reel-wide). These number-dense
# beats are the likely candidates; listen first, then run e.g.
#   generate_audio_kokoro.py <reel> --only B07 --speed 0.94

NARR_M8 = {
    "B00": "Hi, I am Divij Pawar, and this video is about a stricter way to compare two AI agents... and the test it failed. The voice you're hearing is AI generated. The work behind it is mine. So, last video ended on fifteen of sixteen, with fifteen false alarms gone. This week I built a stricter comparator. Then I replayed those same sixteen runs through it. It raised six alarms... and it lost. But along the way, it found two real errors that the winning rule had been quietly hiding. So this one starts with a correction.",
    "B01": "Quick recap, for anyone new. This project runs two AI agents on the same company, and then compares their numbers. For most of its life, most of its alarms were false. Mycroft six counted them. Mycroft seven cut them. Since then, I got a plan approved to turn this agreement detector into a proper audit layer. It has three tiers. Reconcile the figures. Check the accounting. Then classify whatever's left. This video is tier one. And most of it comes down to one test. Two figures can only be compared when four things line up... what it measures, which period, what unit, and where it came from. Miss one, and a match means nothing.",
    "B02": "Let's start with period. I checked what the SEC data layer was actually handing the agents. It asked for the latest value of each figure. And it got back a bare number. No period... no unit. For Apple, revenue was a figure from fiscal twenty eighteen, under a label Apple stopped using years ago. Earnings per share came through as six eighty-eight. That's nine months, added together. The quarter was two oh two. Net income was year to date too. And nothing in the text said so. Every Apple comparison in my last three videos was built on these numbers. Only assets was right.",
    "B03": "So now, every figure travels with its period, its unit, its filing, and the filing's accession number. Quarters get picked by how long they actually last. Year to date is only ever a labelled last resort. And if a company restates a number, the restatement wins. I wrote the failing test first, against a real Apple payload. It pins down both of the wrong picks the old rule made.",
    "B04": "The fourth box is source. The web search tool reports some failures by returning an error message, instead of raising one. My code only watched for raised errors. So a failed search got recorded as... ok. And the error text went straight to the model, as if it were a search result. In Mycroft four, I called this null versus false. This was one step worse. A failure, recorded as a success. The model had invented search settings that contradict each other. Now, one retry with just the query brings back real results.",
    "B05": "Mycroft six said the two agents ran one after the other. Now they run at the same time. The test is simple. Both agents wait at a barrier until the other one arrives. A sequential run could never get there. On a live Apple run, the agents started one millisecond apart. They were in flight together for thirty-nine seconds. I haven't measured a speed-up, though. All this proves is that they overlap. And the server no longer freezes while agents think.",
    "B06": "Next, metric and unit. The new comparator reads each number the way an analyst would. What is this a figure of? Which period? And how close counts as equal? Earnings per share has to match to the cent. Billions get half a percent for rounding. Percentage changes get a tenth of a point. If two agents quote different quarters, that shows up as different periods. In a test built from Microsoft's filing, eighty-two point nine billion and eighty-two billion, eight hundred eighty-six million now count as one figure. And on a stored Nvidia run, a model rating its own confidence at ninety percent had raised the alarm. That number doesn't count as a figure anymore.",
    "B07": "Mycroft seven ended on an open problem. A real ratio and a made-up one look exactly the same. So now, when only one agent states a ratio, the system recomputes it from that agent's own figures. Two Apple runs claimed an asset turnover of zero point one three... and zero point one two. But their own revenue and assets, in the very same paragraph, work out to zero point six nine. That's more than five times off. And those same runs got net margin right. On two Google runs, return on assets recomputes to eighteen point nine six... against a stated eighteen point eight five. That's close enough. Those get cleared.",
    "B08": "And here's the correction. The old tagger saw the word assets... inside return on assets. So it filed those ratios under assets. Then it skipped them, because assets was a figure only one agent had been given. That's how two wrong ratios slipped through as clean. Fifteen of sixteen still counts. But part of it came from that mistake. So the count stays... and the credit shrinks.",
    "B09": "Before I shipped any of this, I set myself a bar. Replay the sixteen labelled runs. Do no worse than the old rule. And it did worse. The old rule raised one alarm. The new one raised six. One of those six is the real fabrication from Mycroft five. Both rules keep that one. The other five are ratios stated with no components at all. And honestly, I can't tell you who's right. The old runs never recorded what each agent was given.",
    "B10": "So I followed my own rule. For company runs, the new comparison gets computed and shown on every record. But the recorded verdict still comes from the old rule. And the screen always says which rule decided. Making the new rule the default... is a human decision. It's mine to make. Meanwhile, every new run stores what each agent was given. Stored records went from seven fields to fourteen. So the evidence for that decision is piling up on its own.",
    "B11": "Live runs also turned up three format problems. First, agents were copying the prompt's own instructions into their answers. Seventeen of a hundred thirty-five stored conclusions had done it. The fix put nothing inside the answer tags... plus a check that rejects copied text. Second, one prompt version made the model close its answer with square brackets. That hit three of twenty-two first attempts. And third, when the model opened its reasoning in the same turn as a web search, that opening got dropped. The parser now reads the earlier turns too. The final batch had zero first-attempt failures, across eight agents.",
    "B12": "In Mycroft six, I said every line of interface code had zero tests. The new interface is built in React. It has seventy-four. Each figure gets its own row. Agent A is in blue. Agent B is in orange. The difference sits right between them. And figures that only one agent was given get folded away, so they never pass for disagreement. The headline is counted straight from the rows. No model writes it.",
    "B13": "Mycroft six found the root cause behind every false alarm. The two agents were never handed the same figure. So now, both of them get net income and diluted earnings per share. And on Apple, for the first time in company mode, both agents cited the same figure, from the same filing. They agreed... and so did the filing. But on Nvidia and Google, one agent said that figure was missing. It was sitting right there, on the last line of its input.",
    "B14": "So... what's true now that wasn't before? Every figure carries its period, its unit, and its filing. Failed searches get recorded as failures. The two agents run at the same time. Ratios get recomputed. And two real errors surfaced. And three hundred ninety Python tests, plus seventy-four interface tests, all pass.",
    "B15": "And what's still not true? The stricter comparator is still opt-in for company runs. Tagging still works on wording. So some phrasings go unrecognised. The ratio check ignores whether figures are annual or quarterly. Agents still skip figures they were given. And none of this is committed. That was true back in Mycroft six. It's still true... and the pile is bigger.",
    "B16": "So here's the smallest true claim I can make. The comparator got stricter... and it lost its own test. It also caught two errors that the easier rule had hidden. So before you trust any match, ask four questions. What does it measure? Which period? What unit? And where did it come from? Six alarms. One real. Five unknown. And the call on which rule counts... still belongs to a person.",
    "B17": "The rule that lost. Written down, versioned, and executable. Signing off... Divij Pawar.",
}

NARR_M9 = {
    "B00": "Hi, I am Divij Pawar, and this video is about what happens when two AI agents disagree... and a person has to decide. The voice you're hearing is AI generated. The work behind it is mine. So, this run asked two agents a simple question. When did the first Pokémon game reach North America? One said nineteen ninety-eight. The other said nineteen ninety-six. The system flagged it. And then it stopped. It's been waiting for a person ever since. I built the thing that made it wait. And I've left it open... on purpose.",
    "B01": "Quick recap, for anyone new. Part one made the comparison stricter. Figures now get compared by metric, period, unit, and source. Back in Mycroft three, I said you should never resolve what you can't prove is independent. You surface it. Then in Mycroft four, I built the flag. And I said that a flagged contradiction triggers nothing. Well... that stopped being true this week. A gate needs four parts. A trigger you can actually test. A stop that really holds. A named person, with a written reason. And a record that nobody can edit. Leave out any one of those... and all you've got is a warning with extra steps.",
    "B02": "The trigger is narrow. A run only waits when two agents cite different values for the same figure and the same period. If only one agent mentions a figure, it gets shown for review. But it doesn't stop anything. With only one answer, there's nothing to decide between. And runs stored before the gate existed never get gated after the fact. Changing the rules on old records is how audit trails get rewritten. In practice, most runs never gate. In the last company batch, none did. There were no mismatches.",
    "B03": "The decision form opens right where you're already reading. Nothing covers up the evidence. The reviewer picks one of five outcomes. Agent A is right. Agent B is right. Both are wrong. There's no real conflict. Or... here's the correct value. Each disputed figure gets its own checkbox, so the decision says exactly what it covers. Then the reviewer writes down why. Twenty characters, minimum. Looks good... is too short, on purpose. And then they type their name.",
    "B04": "But look at the small print. Recorded as entered. Not verified. The login carries a permission level. It doesn't carry a person. So the screen says that, every single time. And if a decision breaks a rule, it gets refused, with the reason spelled out in words. A decision about a figure nobody disputed gets refused. Nothing gets quietly fixed.",
    "B05": "A later decision can supersede an earlier one. But both of them stay on the record. The database itself blocks edits and deletes, the way I set it up back in Mycroft one.",
    "B06": "So what does an investor see while a run is waiting? The agreed figures, and a notice. The server withholds the disputed values and both agents' answers. Then I searched the investor response for both years. Nineteen ninety-six never shows up. But nineteen ninety-eight... shows up once. It's sitting inside a search result the agent read, in the run's trace. And the trace isn't withheld yet. So the gate has a hole in it. And now, it's written down. There's a second limit, too. A read with no token gets the run's stored level. So the withholding is only as strong as read access.",
    "B07": "The coding agent that built all of this never recorded a decision on that run. Clearing a human's gate is the one thing the gate exists to stop. So the Pokémon run... is still open.",
    "B08": "Now, two agents can agree and still both be wrong. So each agent's figures also go through accounting rules. Some of those rules are identities. Basic earnings per share can't be lower than diluted. Free cash flow is operating cash flow, minus capital spending. Assets equal liabilities plus equity. Break one of those, and the run waits for a person, just like a mismatch. The choices change a little, too. The reviewer can confirm the error, instead of picking an agent.",
    "B09": "Every figure an agent cites is also checked against the filing it was given. Rounding to the digits written is fine. In one Microsoft run, an agent was handed eighty-two point nine billion. It wrote down eight hundred twenty-eight point nine. That attempt failed its format check first. So this check never actually ran on it live. But it would have caught it.",
    "B10": "Other rules are only usually true. On Google, net income came out at nearly three times operating income. And the filing said so too. That's a real one-off gain. So soft rules like that never stop a run. They just say... unusual, worth a look. And that also explained two figures that part one left unrecognised. They were Google's filed earnings per share.",
    "B11": "The filing itself goes through the same checks, using the one fetch that was already made. Apple's balance sheet adds up. And then, right in the middle of testing, the local model stopped responding. A five token test request got no reply in sixty seconds. Model calls have no timeout. So a stuck model can hold up a comparison forever. That's in the ledger now.",
    "B12": "Every figure the agents were given can now be found in the filing itself. The system opens the actual SEC document and finds the exact tagged value. It gives back the row, the column, and the number exactly as filed. In the last batch, it found all twenty-four figures. And every filed value matched what the agents were handed. For web figures, it gives back the snippet the agent actually read. The click-through view is the next step. It isn't built yet.",
    "B13": "And you can watch a comparison happen, live. Each agent gets its own lane, showing what it's doing right now. The one shared SEC fetch is drawn once... because it only happened once. Every indicator is a real server event.",
    "B14": "Analysts don't stop at figures, though. They make a call. So the agents now end with a structured assessment. A grade. A direction. Their assumptions. And three key points. When an agent skips it, the screen shows you its raw output... and exactly where the missing piece should be.",
    "B15": "When two grades differ, the system sorts out the cause. Maybe they used different figures, or different periods. Maybe they used the same figures, with different assumptions. Or maybe it's neither. Then it comes down to weighting. In Mycroft three, I sorted disagreements by how they look. This sorts them by where they came from. A consensus only gets recorded when the grades match and no hard rule failed. Anything else goes to the gate. And the reviewer can now set the grade.",
    "B16": "The review now reads in the order a person actually needs it. First, the answer, and whether anything failed a check. Then, the decision. Then the evidence, figure by figure. Then the agents. And then the machinery, folded away. And every review exports as a plain document.",
    "B17": "So... what's true now that wasn't before? A mismatch stops the run until a person decides. Decisions need a reason. And they can't be edited. Investors don't receive the disputed values, or either answer. Accounting rules check each agent and the filing. Soft rules inform. They never block.",
    "B18": "And what's still not true? The decider's name is typed in, and never verified. Anyone can mint a reviewer token. That's one of the critical security findings from the very start. A search result in the trace can still show a disputed value. The storage still holds everything. Withholding only happens when the data is read. No accounting check has stopped a live run yet. Model calls still have no timeout. And none of it... is committed.",
    "B19": "Four videos ago, I said the judgment stays with the human. This is the first time the system can't move without one. So here's the smallest true claim I can make. The machine fetches, reads, compares, and checks. And then... it stops. If you run agents, find one warning your system raises. Give it a trigger, a stop, a person, and a record. Then check that it can't clear itself. One run... still open.",
    "B20": "One run, still open. Written down, versioned, and executable. Signing off... Divij Pawar.",
}

SPEED_IF_SLURRED_M8 = {b: 0.94 for b in ("B02", "B05", "B06", "B07", "B09", "B11", "B14")}
SPEED_IF_SLURRED_M9 = {b: 0.94 for b in ("B06", "B09", "B10", "B12")}
